version: 0.2

phases:
  install:
    runtime-versions:
       nodejs: 14
  build:
    commands:
      - yarn config set cache-folder /root/.yarn-cache
      - yarn install --frozen-lockfile
      - yarn generate --frozen-lockfile
  artifacts:
    files: ./dist/**
cache:
  paths:
    - '/root/.yarn-cache/**/*'
    - 'node_modules/**/*'

